config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'about', to: 'pages#about'
  get 'resume', to: 'pages#resume'
  get 'admin', to: 'admin#index'
  get 'login', to: 'sessions#new'

  resources :sessions, only: [:create]
  resources :projects, only: [:show], controller: 'admin/projects'

  namespace :admin do
    resources :projects, except: [:show]
    resources :settings, only: [:edit, :update]
    resources :resumes, only: [:create, :update]
    get 'resume', to: 'resumes#edit'
  end
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :images, inverse_of: :project, dependent: :destroy

  accepts_nested_attributes_for :images, allow_destroy: true
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < AdminController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate, only: :show

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all.order(:order)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    ids = Project.order(:order).pluck(:id)
    index = ids.index(@project.id)
    @prev_id = index == 0 ? ids[ids.length - 1] : ids[index - 1]
    @next_id = index == ids.length - 1 ? ids[0] : ids[index + 1]
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to edit_admin_project_path(@project), notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to edit_admin_project_path(@project), notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to admin_projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :tagline, :company, :summary, :role, :media, :order, :video_id, images_attributes: [:id, :file, :feature, :order, :_destroy])
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :company, :summary, :role, :media)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/admin/projects/_form.html.erb
<div class="project-form-wrap">
  <%= form_with(model: [:admin, project], local: true) do |form| %>
    <% if project.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

        <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, id: :project_name %>
    </div>

    <div class="field">
      <%= form.label :tagline %>
      <%= form.text_field :tagline, id: :project_tagline %>
    </div>

    <div class="field">
      <%= form.label :company %>
      <%= form.text_field :company, id: :project_company %>
    </div>

    <div class="field">
      <%= form.label :order %>
      <%= form.text_field :order, id: :project_order %>
    </div>

    <div class="field">
      <%= form.label :summary %>
      <%= form.text_area :summary, id: :project_summary %>
    </div>

    <div class="field">
      <%= form.label :role %>
      <%= form.text_area :role, id: :project_role %>
    </div>

    <div class="field">
      <%= form.label :media %>
      <%= form.text_area :media, id: :project_media %>
    </div>

    <div class="field">
      <%= form.label :video_id, 'Video ID' %>
      <%= form.text_field :video_id, id: :project_video_id %>
    </div>

    <h2>Images</h2>
    <div class="add">
      <%= link_to_add_association 'Add Image', form, :images, data: { 'association-insertion-node': 'div#image-fields', 'association-insertion-method': 'append' } %>
    </div>

    <div id="image-fields">
      <%= form.fields_for :images do |image_form| %>
        <%= render 'image_fields', f: image_form %>
      <% end %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

  <%= tinymce %>
</div>

app/views/admin/projects/_image_fields.html.erb
<div class="nested-fields">
  <div class="field image-field">
    <% if f.object.try(:file_url) %>
      <img src="<%= f.object.file_url %>" />
    <% else %>
      <%= f.label :file %>
      <%= f.file_field :file %>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :feature %>
    <%= f.check_box :feature %>
  </div>

  <div class="field">
    <%= f.label :order %>
    <%= f.text_field :order %>
  </div>

  <%= link_to_remove_association 'Remove Image', f %>
</div>

app/views/admin/projects/edit.html.erb
<p id="notice"><%= notice %></p>

<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', admin_projects_path %>

app/views/admin/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Order</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.order %></td>
        <td><%= link_to 'Edit', edit_admin_project_path(project) %></td>
        <td><%= link_to 'Destroy', admin_project_path(project), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', '/admin' %>
<%= link_to 'New Project', new_admin_project_path %>

app/views/admin/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', admin_projects_path %>

app/views/admin/projects/show.html.erb
<div class="project">
  <div class="left">
    <%= link_to image_tag('Button_ArrowLeft.png'), project_path(@prev_id), class: 'arrow prev' %>
    <%= link_to image_tag('Button_ArrowRight.png'), project_path(@next_id), class: 'arrow next' %>
    <h1><%= @project.name %></h1>
    <h3><%= @project.company %></h3>
    <h2>Summary</h2>
    <% if @project.summary.strip.length > 0 %>
      <div class="summary fr-view">
        <%= @project.summary.html_safe %>
      </div>
    <% end %>
    <% if @project.role.strip.length > 0 %>
      <h2>My Role</h2>
      <div class="role fr-view">
        <%= @project.role.html_safe %>
      </div>
    <% end %>
    <% if @project.media.strip.length > 0 %>
      <h2>Media</h2>
      <div class="media fr-view">
        <%= @project.media.html_safe %>
      </div>
    <% end %>
  </div>
  <div class="right">
    <% if @project.images.where(feature: false).any? || @project.video_id %>
      <% imageToCheck = @project.images.where(feature: false).order(:order).first %>
      <div class="gallery-wrapper">
        <div class="gallery">
          <% if @project.video_id && @project.video_id.length > 0 %>
            <div>
              <div class="video-wrapper">
                <iframe src="https://youtube.com/embed/<%= @project.video_id %>?autoplay=1&modestbranding=1&mute=1" frameborder="0" allowfullscreen></iframe>
              </div>
            </div>
          <% end %>
          <% @project.images.where(feature: false).order(:order).each do |image| %>
            <div class="image-wrap">
              <div style="max-width:<%= image.width < image.height ? '50%' : '100%' %>;display:inline-block">
                <img src="<%= image.file_url %>" />
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>