config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'about', to: 'pages#about'
  get 'resume', to: 'pages#resume'
  get 'admin', to: 'admin#index'
  get 'login', to: 'sessions#new'

  resources :sessions, only: [:create]
  resources :projects, only: [:show], controller: 'admin/projects'

  namespace :admin do
    resources :projects, except: [:show]
    resources :settings, only: [:edit, :update]
    resources :resumes, only: [:create, :update]
    get 'resume', to: 'resumes#edit'
  end
end

app/models/setting.rb
class Setting < ApplicationRecord
  mount_uploader :resume, ResumeUploader
  mount_uploader :headshot, ImageUploader
  mount_uploader :about_image, ImageUploader
end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < AdminController
  before_action :set_setting, only: [:update, :edit]

  def edit
  end

  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to edit_admin_setting_path(@setting), notice: 'Settings successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  private

    def set_setting
      @setting = Setting.first
    end

    def setting_params
      params.require(:setting).permit(:headshot, :resume, :youtube, :linkedin, :email, :twitter, :about, :about_image, :available)
    end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/admin/settings/_form.html.erb
<div class="setting-form-wrap">
  <%= form_with(model: [:admin, setting], local: true) do |form| %>
    <% if setting.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(setting.errors.count, "error") %> prohibited these settings from being saved:</h2>

        <ul>
        <% setting.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :headshot %>
      <%= form.file_field :headshot %>
    </div>

    <div class="field">
      <%= form.label :resume %>
      <%= form.file_field :resume %>
    </div>

    <div class="field">
      <%= form.label :youtube %>
      <%= form.text_field :youtube %>
    </div>

    <div class="field">
      <%= form.label :linkedin %>
      <%= form.text_field :linkedin %>
    </div>

    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email %>
    </div>

    <div class="field">
      <%= form.label :twitter %>
      <%= form.text_field :twitter %>
    </div>

    <div class="field">
      <%= form.label :about_image %>
      <%= form.file_field :about_image %>
    </div>

    <div class="field">
      <%= form.label :about %>
      <%= form.text_area :about %>
    </div>

    <div class="field">
      <%= form.label :available %>
      <%= form.check_box :available %>
    </div>

    <div class="actions">
      <%= form.submit 'Update Settings' %>
    </div>
  <% end %>

  <%= tinymce %>
</div>

app/views/admin/settings/edit.html.erb
<p id="notice"><%= notice %></p>

<h1>Editing Settings</h1>

<%= render 'form', setting: @setting %>

<%= link_to 'Back', admin_path %>