config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'about', to: 'pages#about'
  get 'resume', to: 'pages#resume'
  get 'admin', to: 'admin#index'
  get 'login', to: 'sessions#new'

  resources :sessions, only: [:create]
  resources :projects, only: [:show], controller: 'admin/projects'

  namespace :admin do
    resources :projects, except: [:show]
    resources :settings, only: [:edit, :update]
    resources :resumes, only: [:create, :update]
    get 'resume', to: 'resumes#edit'
  end
end

app/controllers/admin/resumes_controller.rb
class Admin::ResumesController < AdminController
  before_action :set_resume, only: [:update]
  def edit
    if Resume.any?
      @resume = Resume.first
    else
      @resume = Resume.new
    end
  end

  def create
    @resume = Resume.new(resume_params)

    respond_to do |format|
      if @resume.save
        flash[:notice] = 'Resume was successfully updated.'
        format.html { redirect_to action: :edit }
      else
        format.html { render :edit }
      end
    end
  end

  def update
    respond_to do |format|
      if @resume.update(resume_params)
        flash[:notice] = 'Resume was successfully updated.'
        format.html { redirect_to action: :edit }
      else
        format.html { render :edit }
      end
    end
  end

  private

  def set_resume
    @resume = Resume.find(params[:id])
  end

  def resume_params
    params.require(:resume).permit(:file)
  end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :set_resume, only: [:update]
  def edit
    if Resume.any?
      @resume = Resume.first
    else
      @resume = Resume.new
    end
  end

  def create
    @resume = Resume.new(resume_params)

    respond_to do |format|
      if @resume.save
        flash[:notice] = 'Resume was successfully updated.'
        format.html { redirect_to action: :edit }
      else
        format.html { render :edit }
      end
    end
  end

  def update
    respond_to do |format|
      if @resume.update(resume_params)
        flash[:notice] = 'Resume was successfully updated.'
        format.html { redirect_to action: :edit }
      else
        format.html { render :edit }
      end
    end
  end

  private

  def set_resume
    @resume = Resume.find(params[:id])
  end

  def resume_params
    params.require(:resume).permit(:file)
  end
end

app/helpers/resume_helper.rb
module ResumeHelper
end

app/views/admin/resumes/_form.html.erb
<%= form_with(model: resume, url: admin_resumes_path, local: true) do |form| %>
  <% if resume.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resume.errors.count, "error") %> prohibited this resume from being saved:</h2>

      <ul>
      <% resume.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :file %>
    <%= form.file_field :file %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/resumes/edit.html.erb
<p id="notice"><%= notice %></p>

<h1>Update Resume</h1>

<%= render 'form', resume: @resume %>

<%= link_to 'Back', '/admin' %>